//
// Created by gribk on 29.10.2023.
//

#ifndef STRUCTURESANDALGORITHMSFORDATAPROCESSING_PRACTICE5_H
#define STRUCTURESANDALGORITHMSFORDATAPROCESSING_PRACTICE5_H


class Practice5 {
public:
    static void start();
};


#endif //STRUCTURESANDALGORITHMSFORDATAPROCESSING_PRACTICE5_H
