//
// Created by gribk on 29.10.2023.
//

#ifndef STRUCTURESANDALGORITHMSFORDATAPROCESSING_BINARYSEARCHTREE_H
#define STRUCTURESANDALGORITHMSFORDATAPROCESSING_BINARYSEARCHTREE_H

#include "BinaryTree.h"

class BinarySearchTree : public BinaryTree {

};


#endif //STRUCTURESANDALGORITHMSFORDATAPROCESSING_BINARYSEARCHTREE_H
